target 'BHMovie' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'MJRefresh', '~> 3.1.10'
pod 'JSONModel', '~> 1.2.0'
#pod 'MobileVLCKit', '~> 2.2.2'
pod 'BmobSDK'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Masonry', '~> 1.0.1'
pod 'ZFPlayer'
pod 'HYBNetworking', '~> 3.3.0'
pod 'FreeStreamer','~> 3.7.2'
pod 'Bugly'
pod 'TYPagerController' , '~> 2.0.1'
pod 'ZFDownload'
end
